### ISSUE TITLE
Some files updated

### ISSUE THREAD

**Issue by rykahsay** [yoftil7/project_3#1]
Please follow these steps:

### Downloads
- Download the files I have uploaded "record.py" and "db.py" under your "inventory/" folder (you will be overwriting "record.py") 
- Download the file I have uploaded "run.sh" and over write the copy you already have
- Download record_search.json and put it under tests/queries/
- Download record_insert.json and put it under tests/queries/

### Building and starting the service
```
$ sh build.sh
$ sh run.sh
```

### Your mongodb
You need to have a mongo database named "inventorydb" which can be accessed using authentication credentials username="inventorydbusername" and password="inventorydbpassword"

This information is passed to your flask app in the file "instance/config.dev.py"

### Install httpie
```
sudo pip3 install httpie
```

### Testing the APIs
```
http POST :5000/record/insert < tests/queries/record_insert.json
http POST :5000/record/search < tests/queries/record_search.json
```

Now, look how I have implemented insert and search in "record.py"

**Comment by yoftil7** [comment]
I have updated records.py with the rest of the (Read, Update, and Delete) endpoints. 

**This is the modified, 'record.py' file.**
[record.py.tar.gz](https://github.com/yoftil7/project_3/files/15377091/record.py.tar.gz)

**Comment by yoftil7** [comment]
- The necessary APIs have been successfully added to inventory/record.py, and corresponding test queries have been included in tests/queries. 
- However, while the individual APIs are functional, the overall program is currently not running. 
- Probable causes: compatibility issues! 

I'm actively trying to address the issue, but any suggestions would be greatly appreciated.

**Comment by rykahsay** [comment]
fsadfaf

```
0) Change bindIp to 0.0.0.0 in /etc/mongod.conf
    $ sudo vi /etc/mongod.conf

1) Start MongoDB without authentication and comment these two lines
    
    $ sudo vi /etc/mongod.conf
        #security:
        #   authorization: "enabled"    
    $ sudo systemctl restart mongod
      OR
    $ brew services start mongodb-community@6.0

2) Start mongo console and add superadmin user with
   
    $ use admin
    $ db.createUser({ user: "superadmin", pwd: "superpass", roles: ["userAdminAnyDatabase", "dbAdminAnyDatabase", "readWriteAnyDatabase"]})

3) Start MongoDB with authentication (uncomment the security lines in /etc/mongod.conf)
    >> sudo vi /etc/mongod.conf
            security:
                authorization: "enabled"
    >> sudo systemctl restart mongod


4) Start mongo, authenticate as superadmin to create new user inventorydbadmin
    > use admin
    > db.auth("superadmin", "superpass")
    > use inventorydb
    > db.createUser({user: "inventorydbusername", pwd: "inventorydbpassword", roles: [ { role: "readWrite", db: "inventorydb" } ]})



5) Login
    $ mongosh --username inventorydbusername --password inventorydbpassword --authenticationDatabase inventorydb
    

    > use inventorydb
    > show collections


```

**Comment by rykahsay** [comment]
How to check that your app is running:

```
$ ps -aef | grep flask
  503 86081     1   0 Fri12PM ??         0:24.65 /opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python -m flask run -h localhost -p 5000
```

**Comment by rykahsay** [comment]
Copy paste this code in a file named "connect.py" and try to run it as "python3 connect.py"

```
import pymongo
import json


def main():

    DB_NAME = "inventorydb"
    DB_USERNAME = "inventorydbusername"
    DB_PASSWORD = "inventorydbpassword"
    MONGODB_CONNSTRING = "mongodb://%s:%s@localhost:27017/?authSource=%s" % (DB_USERNAME, DB_PASSWORD,DB_NAME)

    ret_obj, error_obj = {}, {}
    try:
        client = pymongo.MongoClient(MONGODB_CONNSTRING)
        client.server_info()
        mongo_dbh = client[DB_NAME]
        for doc in mongo_dbh["c_inventory"].find({}):
            if "_id" in doc:
                doc["_id"] = str(doc["_id"])
            print (json.dumps(doc, indent=4))

    except pymongo.errors.ServerSelectionTimeoutError as err:
        error_obj = {"status":0, "error":"Connection to MongoDB failed", "details":err.details}
    except pymongo.errors.OperationFailure as err:
        error_obj = {"status":0, "error":"Connection to MongoDB failed", "details":err.details}

    return



if __name__ == '__main__':
    main()

```

**Comment by yoftil7** [comment]
Ok bro. Thanks

**Comment by rykahsay** [comment]
If that doesn't work, try this one:

```
import pymongo
import json


def main():

    DB_NAME = "inventorydb"
    DB_USERNAME = "inventorydbusername"
    DB_PASSWORD = "inventorydbpassword"
    HOST = "mongodb://localhost:27017" 
    
    try:
        client = pymongo.MongoClient(
            HOST,
            username=DB_USERNAME,
            password=DB_PASSWORD,
            authSource=DB_NAME,
            authMechanism='SCRAM-SHA-1',
            serverSelectionTimeoutMS=10000
        )
        client.server_info()
        mongo_dbh = client[DB_NAME]
        for doc in mongo_dbh["c_inventory"].find({}):
            if "_id" in doc:
                doc["_id"] = str(doc["_id"])
            print (json.dumps(doc, indent=4))

    except pymongo.errors.ServerSelectionTimeoutError as err:
        error_obj = {"status":0, "error":"Connection to MongoDB failed", "details":err.details}
    except pymongo.errors.OperationFailure as err:
        error_obj = {"status":0, "error":"Connection to MongoDB failed", "details":err.details}

    return



if __name__ == '__main__':
    main()
```

**Comment by yoftil7** [comment]
### **build.sh**
lwamy@LWAMs-MacBook-Air project_3 % sh build.sh
running bdist_wheel
running build
running build_py
copying inventory/db.py -> build/lib/inventory
running egg_info
writing inventory.egg-info/PKG-INFO
writing dependency_links to inventory.egg-info/dependency_links.txt
writing requirements to inventory.egg-info/requires.txt
writing top-level names to inventory.egg-info/top_level.txt
reading manifest file 'inventory.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no directories found matching 'inventory/conf'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'inventory.egg-info/SOURCES.txt'
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
installing to build/bdist.macosx-10.9-universal2/wheel
running install
running install_lib
creating build/bdist.macosx-10.9-universal2/wheel
copying build/lib/.DS_Store -> build/bdist.macosx-10.9-universal2/wheel
creating build/bdist.macosx-10.9-universal2/wheel/inventory
copying build/lib/inventory/db.py -> build/bdist.macosx-10.9-universal2/wheel/inventory
copying build/lib/inventory/__init__.py -> build/bdist.macosx-10.9-universal2/wheel/inventory
copying build/lib/inventory/record.py -> build/bdist.macosx-10.9-universal2/wheel/inventory
running install_egg_info
Copying inventory.egg-info to build/bdist.macosx-10.9-universal2/wheel/inventory-1.0-py3.12.egg-info
running install_scripts
creating build/bdist.macosx-10.9-universal2/wheel/inventory-1.0.dist-info/WHEEL
creating 'dist/inventory-1.0-py3-none-any.whl' and adding 'build/bdist.macosx-10.9-universal2/wheel' to it
adding '.DS_Store'
adding 'inventory/__init__.py'
adding 'inventory/db.py'
adding 'inventory/record.py'
adding 'inventory-1.0.dist-info/METADATA'
adding 'inventory-1.0.dist-info/WHEEL'
adding 'inventory-1.0.dist-info/top_level.txt'
adding 'inventory-1.0.dist-info/RECORD'
removing build/bdist.macosx-10.9-universal2/wheel
lwamy@LWAMs-MacBook-Air project_3 % 

### **run.sh**
lwamy@LWAMs-MacBook-Air project_3 % sh run.sh

### **ps -aef | grep flask**
lwamy@LWAMs-MacBook-Air project_3 % ps -aef | grep flask
  501 49870 49829   0 11:08PM ttys000    0:00.00 grep flask

**### Test queries** 
lwamy@LWAMs-MacBook-Air project_3 % http POST :5000/record/insert < tests/queries/record_insert.json

### **error:**
http: error: ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /record/insert (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102f7eff0>: Failed to establish a new connection: [Errno 61] Connection refused')) while doing a POST request to URL: http://localhost:5000/record/insert
